export const SEARCH_CONTENT = "SEARCH_CONTENT";
export const SEARCH_TYPE = "SEARCH_TYPE";
export const RESULT_FILTER_DATE = "RESULT_FILTER_DATE";
export const RESULT_FILTER_NAME = "RESULT_FILTER_NAME";
export const SET_RESULT = "SET_RESULT";
export const TURN_PAGE = "TURN_PAGE";
export const SET_PAGE="SET_PAGE";
